name: devsteam_mobi_test
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  material_design_icons_flutter: ^4.0.5855
  sqflite: ^1.3.2+3
  path_provider: ^1.6.27
  path: ^1.7.0
  flutter_form_builder: ^4.2.0
  contacts_service: ^0.4.6
  permission_handler: ^5.1.0+2
  provider: ^4.3.3
  intl: 0.16.1
  image_picker: ^0.6.6+5
  syncfusion_flutter_signaturepad: ^18.4.47-beta
  printing: 4.1.0
  pdf: ^2.1.0
  mailer: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true