name: devsteam_mobi_test
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  material_design_icons_flutter: ^4.0.5855
  sqflite: ^1.3.2+3
  path_provider: ^1.6.27
  path: ^1.7.0
  flutter_form_builder: ^4.2.0
  contacts_service: ^0.4.6
  permission_handler: ^5.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true